// Questions officielles CSP + CR (examen civique) — fusionnées et dédupliquées
// Source : ministère de l'Intérieur — formation-civique.interieur.gouv.fr
// Les réponses sont des exercices d'entraînement indépendants ; les propositions officielles ne sont pas publiées.
// 'source' indique la ou les listes officielles dont provient la question : ['csp'], ['cr'] ou ['csp','cr']
var CIVIQUE_QUESTIONS = [
  {theme:'Principes et valeurs de la République', question:'À quoi correspond la date du 14 juillet ?', reponse:'Fête nationale : commémoration de la prise de la Bastille (1789) et de la Fête de la Fédération (1790).', source:['csp']},
  {theme:'Principes et valeurs de la République', question:'Quel est l\'un des symboles de la République française ?', reponse:'Le drapeau tricolore, Marianne, le coq gaulois ou la devise « Liberté, égalité, fraternité ».', source:['csp']},
  {theme:'Principes et valeurs de la République', question:'Le principe d\'égalité signifie que :', reponse:'Tous les citoyens ont les mêmes droits et devoirs, sans distinction d\'origine, de sexe ou de religion.', source:['csp']},
  {theme:'Principes et valeurs de la République', question:'"Liberté, égalité, fraternité", c\'est :', reponse:'La devise de la République française.', source:['csp']},
  {theme:'Principes et valeurs de la République', question:'A-t-on le droit d\'insulter publiquement quelqu\'un parce qu\'il est différent (handicap, apparence physique, sexe…) ?', reponse:'Non : c\'est une discrimination interdite et punie par la loi.', source:['csp','cr']},
  {theme:'Principes et valeurs de la République', question:'Certains métiers peuvent-ils être réservés aux hommes ?', reponse:'Non, l\'égalité femmes-hommes interdit de réserver un métier à un seul sexe.', source:['csp']},
  {theme:'Principes et valeurs de la République', question:'De quand date la Constitution de la Ve République ?', reponse:'Du 4 octobre 1958.', source:['csp']},
  {theme:'Principes et valeurs de la République', question:'Le régime de la France est :', reponse:'Une République démocratique, indivisible, laïque et sociale.', source:['csp','cr']},
  {theme:'Principes et valeurs de la République', question:'Lequel de ces symboles représente officiellement la République française ?', reponse:'Réponse selon les propositions : privilégier le drapeau tricolore ou Marianne, symboles officiels.', source:['csp']},
  {theme:'Principes et valeurs de la République', question:'Où peut-on voir la devise de la République ?', reponse:'Sur les frontons des mairies, des écoles et des bâtiments publics, et sur les pièces de monnaie.', source:['csp']},
  {theme:'Principes et valeurs de la République', question:'Quels sont des symboles officiels de la République française ?', reponse:'Le drapeau tricolore, Marianne, le coq gaulois, la Marseillaise et la devise républicaine.', source:['csp','cr']},
  {theme:'Principes et valeurs de la République', question:'Qu\'est-ce que l\'égalité ?', reponse:'Le principe selon lequel tous les citoyens ont les mêmes droits devant la loi.', source:['csp']},
  {theme:'Principes et valeurs de la République', question:'Que signifie la liberté ?', reponse:'Pouvoir agir et penser librement, dans le respect de la loi et des droits d\'autrui.', source:['csp']},
  {theme:'Principes et valeurs de la République', question:'Que signifie le mot "fraternité" dans la devise française ?', reponse:'La solidarité entre tous les citoyens.', source:['csp']},
  {theme:'Principes et valeurs de la République', question:'Quel animal est un symbole de la France ?', reponse:'Le coq gaulois.', source:['csp']},
  {theme:'Principes et valeurs de la République', question:'Quel est l\'un des rôles des associations ?', reponse:'Défendre une cause ou proposer des activités d\'intérêt général.', source:['csp']},
  {theme:'Principes et valeurs de la République', question:'Quel est le nom de l\'hymne national ?', reponse:'La Marseillaise.', source:['csp']},
  {theme:'Principes et valeurs de la République', question:'Quel symbole de la République française est tricolore ?', reponse:'Le drapeau français.', source:['csp']},
  {theme:'Principes et valeurs de la République', question:'Quelle est la date de la fête nationale française ?', reponse:'Le 14 juillet.', source:['csp']},
  {theme:'Principes et valeurs de la République', question:'Quelle est la devise de la République française ?', reponse:'Liberté, Égalité, Fraternité.', source:['csp']},
  {theme:'Principes et valeurs de la République', question:'Quelle est la langue officielle de la République française ?', reponse:'Le français.', source:['csp']},
  {theme:'Principes et valeurs de la République', question:'Quelle est la place de la langue française dans la République ?', reponse:'Elle est la langue officielle de la République, inscrite dans la Constitution (article 2).', source:['csp','cr']},
  {theme:'Principes et valeurs de la République', question:'Quelle liberté permet à chacun d\'exprimer ses idées ?', reponse:'La liberté d\'expression.', source:['csp']},
  {theme:'Principes et valeurs de la République', question:'Quelle proposition est correcte ? La liberté d\'expression :', reponse:'Elle est garantie mais limitée par la loi (diffamation, injure, incitation à la haine).', source:['csp']},
  {theme:'Principes et valeurs de la République', question:'Quelles sont les couleurs du drapeau français ?', reponse:'Bleu, blanc, rouge.', source:['csp']},
  {theme:'Principes et valeurs de la République', question:'Qu\'est-ce que la Marseillaise ?', reponse:'L\'hymne national de la France.', source:['csp','cr']},
  {theme:'Principes et valeurs de la République', question:'Qu\'est ce qui est traditionnellement organisé sur les Champs Élysées le 14 juillet pour célébrer la fête nationale ?', reponse:'Le défilé militaire.', source:['csp']},
  {theme:'Principes et valeurs de la République', question:'Qui est Marianne ?', reponse:'La figure symbolique de la République française.', source:['csp']},
  {theme:'Principes et valeurs de la République', question:'Une personne peut-elle changer librement de religion ?', reponse:'Oui, la liberté de conscience et de culte le garantit.', source:['csp']},
  {theme:'Principes et valeurs de la République', question:'"La France est une République indivisible, ..., démocratique et sociale". Complétez cette phrase extraite de l\'article 1er de la Constitution :', reponse:'« laïque » — République indivisible, laïque, démocratique et sociale.', source:['csp']},
  {theme:'Principes et valeurs de la République', question:'En quelle année la loi de séparation des Églises et de l\'État a-t-elle été votée ?', reponse:'1905.', source:['csp','cr']},
  {theme:'Principes et valeurs de la République', question:'Que permet le principe de laïcité ?', reponse:'La neutralité de l\'État et la liberté de croire ou de ne pas croire.', source:['csp']},
  {theme:'Principes et valeurs de la République', question:'Quel droit est garanti par la laïcité ?', reponse:'La liberté de conscience et de culte.', source:['csp','cr']},
  {theme:'Principes et valeurs de la République', question:'Pourquoi le principe de laïcité doit-il être respecté à l\'école ?', reponse:'Pour garantir la neutralité de l\'enseignement public et l\'égalité entre tous les élèves, quelles que soient leurs convictions.', source:['csp','cr']},
  {theme:'Principes et valeurs de la République', question:'Qu\'est-ce que la laïcité ?', reponse:'La séparation des Églises et de l\'État, et la neutralité religieuse des institutions publiques.', source:['csp']},
  {theme:'Principes et valeurs de la République', question:'Un enfant peut-il refuser d\'aller à l\'école pour une raison religieuse ?', reponse:'Non, l\'instruction est obligatoire quelle que soit la religion.', source:['csp']},
  {theme:'Principes et valeurs de la République', question:'Une personne a-t-elle le droit de ne pas croire en une religion ?', reponse:'Oui, elle peut être athée ou agnostique librement.', source:['csp','cr']},
  {theme:'Système institutionnel et politique', question:'Qui nomme le Premier ministre ?', reponse:'Le président de la République.', source:['csp','cr']},
  {theme:'Système institutionnel et politique', question:'Le Parlement est composé :', reponse:'De l\'Assemblée nationale et du Sénat.', source:['csp','cr']},
  {theme:'Système institutionnel et politique', question:'Qu\'est-ce que le pouvoir exécutif ? Le pouvoir :', reponse:'Le pouvoir qui applique et fait exécuter les lois (président et gouvernement).', source:['csp']},
  {theme:'Système institutionnel et politique', question:'Les dirigeants sont élus par les citoyens dans :', reponse:'Une démocratie.', source:['csp']},
  {theme:'Système institutionnel et politique', question:'A-t-on le droit de ne pas respecter une loi ?', reponse:'Non, la loi s\'applique à tous et sa violation est sanctionnée.', source:['csp']},
  {theme:'Système institutionnel et politique', question:'Qui doit respecter la loi ?', reponse:'Toute personne présente sur le territoire français.', source:['csp']},
  {theme:'Système institutionnel et politique', question:'Quel est le rôle de l\'autorité judiciaire ?', reponse:'Rendre la justice et sanctionner les infractions.', source:['csp']},
  {theme:'Système institutionnel et politique', question:'Quel pouvoir détient un juge ? Le pouvoir :', reponse:'Le pouvoir judiciaire.', source:['csp']},
  {theme:'Système institutionnel et politique', question:'L\'autorité judiciaire est exercée par :', reponse:'Les juges et les tribunaux.', source:['csp']},
  {theme:'Système institutionnel et politique', question:'Que se passe-t-il si un ministre ne respecte pas la loi ?', reponse:'Il peut être poursuivi et jugé comme tout citoyen.', source:['csp','cr']},
  {theme:'Système institutionnel et politique', question:'Qui est élu lors des élections législatives ?', reponse:'Les députés.', source:['csp']},
  {theme:'Système institutionnel et politique', question:'Combien de députés composent l\'Assemblée nationale ?', reponse:'577.', source:['csp','cr']},
  {theme:'Système institutionnel et politique', question:'Quand sont élus les sénateurs ?', reponse:'Au suffrage indirect (par les grands électeurs), avec un renouvellement partiel tous les 3 ans.', source:['csp']},
  {theme:'Système institutionnel et politique', question:'Qui est élu lors des élections municipales ?', reponse:'Les conseillers municipaux, qui élisent ensuite le maire.', source:['csp']},
  {theme:'Système institutionnel et politique', question:'Qui est élu lors des élections présidentielles ?', reponse:'Le président de la République.', source:['csp']},
  {theme:'Système institutionnel et politique', question:'À partir de quel âge a-t-on le droit de voter ?', reponse:'18 ans.', source:['csp']},
  {theme:'Système institutionnel et politique', question:'Pour combien de temps est élu le président de la République française ?', reponse:'5 ans (quinquennat).', source:['csp']},
  {theme:'Système institutionnel et politique', question:'Pour combien de temps sont élus les députés ?', reponse:'5 ans.', source:['csp']},
  {theme:'Système institutionnel et politique', question:'Pour combien de temps sont élus les sénateurs ?', reponse:'6 ans.', source:['csp','cr']},
  {theme:'Système institutionnel et politique', question:'Qui possède le pouvoir exécutif ?', reponse:'Le président de la République et le gouvernement.', source:['csp']},
  {theme:'Système institutionnel et politique', question:'Quelle condition est nécessaire pour voter aux élections ?', reponse:'Être majeur, de nationalité française et inscrit sur les listes électorales.', source:['csp','cr']},
  {theme:'Système institutionnel et politique', question:'Qui peut voter aux élections en France ?', reponse:'Les citoyens français majeurs inscrits sur les listes électorales.', source:['csp','cr']},
  {theme:'Système institutionnel et politique', question:'Que signifie « suffrage universel » ?', reponse:'Tous les citoyens majeurs peuvent voter, sans condition de fortune ou de diplôme.', source:['csp']},
  {theme:'Système institutionnel et politique', question:'Concernant les partis politiques, quelle proposition est correcte ?', reponse:'Ils sont libres de se former et de se présenter aux élections (pluralisme politique).', source:['csp']},
  {theme:'Système institutionnel et politique', question:'Quel est le rôle des députés ?', reponse:'Voter les lois et contrôler l\'action du gouvernement.', source:['csp']},
  {theme:'Système institutionnel et politique', question:'La séparation des pouvoirs est un principe fondamental. Quels sont les trois pouvoirs concernés ?', reponse:'Le pouvoir exécutif, le pouvoir législatif et le pouvoir judiciaire.', source:['csp','cr']},
  {theme:'Système institutionnel et politique', question:'Qui possède le pouvoir législatif ?', reponse:'Le Parlement (Assemblée nationale et Sénat).', source:['csp']},
  {theme:'Système institutionnel et politique', question:'Qui sanctionne l\'auteur d\'un vol ?', reponse:'Le juge / le tribunal (autorité judiciaire).', source:['csp','cr']},
  {theme:'Système institutionnel et politique', question:'Qui élit les députés ?', reponse:'Les citoyens français, au suffrage universel direct.', source:['csp']},
  {theme:'Système institutionnel et politique', question:'Qui vote les lois ?', reponse:'Le Parlement.', source:['csp']},
  {theme:'Système institutionnel et politique', question:'Qui réside au palais de l\'Élysée ?', reponse:'Le président de la République.', source:['csp']},
  {theme:'Système institutionnel et politique', question:'Combien y a-t-il de départements en France ?', reponse:'101 (dont 5 départements et régions d\'outre-mer).', source:['csp']},
  {theme:'Système institutionnel et politique', question:'Qui représente l\'État dans un département ?', reponse:'Le préfet.', source:['csp']},
  {theme:'Système institutionnel et politique', question:'Qui dirige la commune ?', reponse:'Le maire.', source:['csp','cr']},
  {theme:'Système institutionnel et politique', question:'Est-ce que le président de la République a tous les pouvoirs ?', reponse:'Non, ses pouvoirs sont encadrés par la Constitution et partagés avec le gouvernement et le Parlement.', source:['csp','cr']},
  {theme:'Système institutionnel et politique', question:'Qui est le préfet ?', reponse:'Le représentant de l\'État dans un département ou une région.', source:['csp','cr']},
  {theme:'Système institutionnel et politique', question:'Quel est le rôle du Parlement ?', reponse:'Voter les lois et contrôler l\'action du gouvernement.', source:['csp']},
  {theme:'Système institutionnel et politique', question:'Quel est le régime politique de la France aujourd\'hui ?', reponse:'Une République démocratique (Ve République).', source:['csp','cr']},
  {theme:'Système institutionnel et politique', question:'Combien d\'États font partie de l\'Union européenne au 1er janvier 2025 ?', reponse:'27.', source:['csp']},
  {theme:'Système institutionnel et politique', question:'Quel État n\'est pas membre de l\'Union européenne ?', reponse:'Réponse selon les propositions : par exemple le Royaume-Uni (sorti en 2020), la Suisse ou la Norvège.', source:['csp','cr']},
  {theme:'Système institutionnel et politique', question:'Quelle condition est nécessaire pour voter aux élections européennes ?', reponse:'Être citoyen d\'un État membre de l\'Union européenne et majeur.', source:['csp','cr']},
  {theme:'Système institutionnel et politique', question:'À quelle fréquence les élections européennes sont-elles organisées ?', reponse:'Tous les 5 ans.', source:['csp','cr']},
  {theme:'Système institutionnel et politique', question:'Quel pays est un pays fondateur de l\'Union européenne ?', reponse:'La France (avec l\'Allemagne, l\'Italie, la Belgique, les Pays-Bas et le Luxembourg).', source:['csp','cr']},
  {theme:'Système institutionnel et politique', question:'Quelle est la monnaie utilisée en France ?', reponse:'L\'euro.', source:['csp']},
  {theme:'Système institutionnel et politique', question:'Qui élit les députés européens ?', reponse:'Les citoyens des États membres de l\'Union européenne, au suffrage universel direct.', source:['csp']},
  {theme:'Système institutionnel et politique', question:'Quand célèbre-t-on la journée de l\'Europe ?', reponse:'Le 9 mai.', source:['csp','cr']},
  {theme:'Droits et devoirs', question:'Comment s\'appelle la Constitution actuelle de la France ?', reponse:'La Constitution de la Ve République (4 octobre 1958).', source:['csp']},
  {theme:'Droits et devoirs', question:'Comment s\'appelle le texte qui énonce les droits et devoirs des personnes résidant en France ?', reponse:'La Constitution, et la Déclaration des droits de l\'homme et du citoyen de 1789.', source:['csp']},
  {theme:'Droits et devoirs', question:'Concernant les droits individuels, quelle proposition est correcte ?', reponse:'Ils sont garantis à tous, dans le respect des droits d\'autrui et de la loi.', source:['csp']},
  {theme:'Droits et devoirs', question:'De quelle année date la Déclaration des droits de l\'homme et du citoyen ?', reponse:'1789.', source:['csp']},
  {theme:'Droits et devoirs', question:'Lequel de ces droits est un droit fondamental ?', reponse:'Réponse selon les propositions : la liberté d\'expression, l\'égalité devant la loi ou le droit à la sûreté sont des droits fondamentaux.', source:['csp']},
  {theme:'Droits et devoirs', question:'Parmi ces textes, lequel garantit les droits et libertés en France ?', reponse:'La Déclaration des droits de l\'homme et du citoyen de 1789.', source:['csp']},
  {theme:'Droits et devoirs', question:'Qu\'est-ce que la liberté d\'expression ?', reponse:'Le droit de dire, écrire et publier ses opinions, dans le respect de la loi.', source:['csp']},
  {theme:'Droits et devoirs', question:'Quel droit permet à une personne de se défendre devant la justice ?', reponse:'Le droit à un procès équitable et à la défense.', source:['csp']},
  {theme:'Droits et devoirs', question:'Quel est le texte fondateur établissant en France les droits et les devoirs de chaque citoyen ?', reponse:'La Déclaration des droits de l\'homme et du citoyen (1789).', source:['csp']},
  {theme:'Droits et devoirs', question:'Quel texte a été adopté pendant la Révolution française ?', reponse:'La Déclaration des droits de l\'homme et du citoyen (1789).', source:['csp']},
  {theme:'Droits et devoirs', question:'Quelle liberté permet à une personne de ne pas avoir de religion ?', reponse:'La liberté de conscience (elle peut être athée).', source:['csp']},
  {theme:'Droits et devoirs', question:'Une femme peut avorter :', reponse:'Librement, dans les conditions et délais prévus par la loi (IVG).', source:['csp']},
  {theme:'Droits et devoirs', question:'Est-il toujours possible de divorcer ?', reponse:'Oui, le divorce est un droit reconnu par la loi française.', source:['csp','cr']},
  {theme:'Droits et devoirs', question:'La peine de mort est :', reponse:'Abolie en France depuis 1981.', source:['csp','cr']},
  {theme:'Droits et devoirs', question:'Concernant les limites aux libertés individuelles, quelle proposition est correcte ?', reponse:'Elles peuvent être limitées par la loi pour protéger l\'ordre public ou les droits d\'autrui.', source:['csp']},
  {theme:'Droits et devoirs', question:'En France, est-ce légal d\'être marié à plusieurs personnes en même temps ?', reponse:'Non, la polygamie est interdite.', source:['csp']},
  {theme:'Droits et devoirs', question:'Faut-il réduire ses déchets ?', reponse:'Oui, c\'est un geste citoyen utile pour protéger l\'environnement.', source:['csp']},
  {theme:'Droits et devoirs', question:'Jeter une bouteille dans la rue est :', reponse:'Une infraction (incivilité sanctionnée par une amende).', source:['csp']},
  {theme:'Droits et devoirs', question:'Pourquoi les libertés individuelles peuvent-elles être limitées ?', reponse:'Pour protéger l\'ordre public, la sécurité et les droits des autres personnes.', source:['csp']},
  {theme:'Droits et devoirs', question:'Que doit faire une personne en cas d\'accident ?', reponse:'Porter secours si possible et alerter les secours (15, 17, 18 ou 112).', source:['csp']},
  {theme:'Droits et devoirs', question:'Que permet la citoyenneté française ?', reponse:'De voter, d\'être élu, d\'accéder à certains emplois publics et de bénéficier de la protection de l\'État.', source:['csp']},
  {theme:'Droits et devoirs', question:'Que risque une personne qui ne respecte pas la loi ?', reponse:'Des sanctions pénales (amende ou prison selon la gravité de l\'infraction).', source:['csp']},
  {theme:'Droits et devoirs', question:'Quel est le rôle de la gendarmerie ?', reponse:'Assurer la sécurité, notamment en zone rurale et périurbaine.', source:['csp']},
  {theme:'Droits et devoirs', question:'Quel est le rôle de la police ?', reponse:'Assurer la sécurité et l\'ordre public, et faire respecter la loi.', source:['csp','cr']},
  {theme:'Droits et devoirs', question:'Qu\'est-ce qu\'une infraction ?', reponse:'Un acte interdit par la loi et sanctionné (contravention, délit ou crime).', source:['csp']},
  {theme:'Droits et devoirs', question:'Comment peut-on réduire ses déchets ?', reponse:'En triant, en recyclant et en limitant les emballages et le gaspillage.', source:['csp']},
  {theme:'Droits et devoirs', question:'Déposer une machine à laver cassée sur le trottoir est :', reponse:'Une infraction (dépôt sauvage sanctionné par une amende).', source:['csp']},
  {theme:'Droits et devoirs', question:'En quoi consiste la traite des êtres humains ?', reponse:'L\'exploitation d\'une personne (travail forcé, prostitution…) contre son gré ; c\'est un crime.', source:['csp']},
  {theme:'Droits et devoirs', question:'Que doit faire une victime de violences ?', reponse:'Porter plainte auprès de la police ou de la gendarmerie et se faire soigner ou aider.', source:['csp','cr']},
  {theme:'Droits et devoirs', question:'Quelle est l\'infraction la plus grave ?', reponse:'Le crime.', source:['csp','cr']},
  {theme:'Histoire, géographie et culture', question:'En quelle année a débuté la Révolution française ?', reponse:'1789.', source:['csp']},
  {theme:'Histoire, géographie et culture', question:'Qui était Napoléon Ier ?', reponse:'Un général devenu empereur des Français (1804-1815).', source:['csp']},
  {theme:'Histoire, géographie et culture', question:'Lequel de ces personnages historiques est français ?', reponse:'Réponse selon les propositions (ex. : Napoléon, Charles de Gaulle).', source:['csp']},
  {theme:'Histoire, géographie et culture', question:'Dans quelle République est-on aujourd\'hui ?', reponse:'La Ve République.', source:['csp']},
  {theme:'Histoire, géographie et culture', question:'Qu\'est-ce que la Shoah ?', reponse:'L\'extermination des Juifs d\'Europe par les nazis pendant la Seconde Guerre mondiale.', source:['csp']},
  {theme:'Histoire, géographie et culture', question:'Quel pays ou région du monde a été colonisé par la France ?', reponse:'Réponse selon les propositions (ex. : l\'Algérie, le Vietnam, une partie de l\'Afrique).', source:['csp']},
  {theme:'Histoire, géographie et culture', question:'Qui a rendu l\'école gratuite, laïque et obligatoire ?', reponse:'Jules Ferry.', source:['csp']},
  {theme:'Histoire, géographie et culture', question:'Quand a eu lieu la Seconde Guerre mondiale ?', reponse:'De 1939 à 1945.', source:['csp']},
  {theme:'Histoire, géographie et culture', question:'Quand a eu lieu la Première Guerre mondiale ?', reponse:'De 1914 à 1918.', source:['csp']},
  {theme:'Histoire, géographie et culture', question:'En quelle année a été créée la Communauté Économique Européenne (CEE) ?', reponse:'1957 (traité de Rome).', source:['csp']},
  {theme:'Histoire, géographie et culture', question:'Le 11 novembre est un jour férié. À quoi correspond cette date ?', reponse:'L\'armistice de 1918, marquant la fin de la Première Guerre mondiale.', source:['csp']},
  {theme:'Histoire, géographie et culture', question:'Qui a été le premier Président élu sous la Ve République ?', reponse:'Charles de Gaulle.', source:['csp']},
  {theme:'Histoire, géographie et culture', question:'En quelle année l\'esclavage a-t-il été aboli définitivement en France ?', reponse:'1848.', source:['csp']},
  {theme:'Histoire, géographie et culture', question:'Depuis quelle année l\'école publique est-elle gratuite ?', reponse:'1881 (lois de Jules Ferry).', source:['csp']},
  {theme:'Histoire, géographie et culture', question:'Combien y a-t-il eu de républiques en France ?', reponse:'5.', source:['csp']},
  {theme:'Histoire, géographie et culture', question:'Qui était le roi de France au moment de la Révolution française ?', reponse:'Louis XVI.', source:['csp']},
  {theme:'Histoire, géographie et culture', question:'Qui a fondé la Ve République ?', reponse:'Charles de Gaulle.', source:['csp']},
  {theme:'Histoire, géographie et culture', question:'Que célèbre-t-on le 14 juillet ?', reponse:'La prise de la Bastille (1789) et la Fête de la Fédération.', source:['csp']},
  {theme:'Histoire, géographie et culture', question:'Quelle guerre a eu lieu entre 1914 et 1918 ?', reponse:'La Première Guerre mondiale.', source:['csp']},
  {theme:'Histoire, géographie et culture', question:'Pourquoi l\'année 1958 est importante pour la France ?', reponse:'C\'est l\'année de la Constitution qui a fondé la Ve République.', source:['csp']},
  {theme:'Histoire, géographie et culture', question:'Quel fleuve coule en France ?', reponse:'Réponse selon les propositions (ex. : la Seine, la Loire, le Rhône).', source:['csp']},
  {theme:'Histoire, géographie et culture', question:'Quelle ville est française ?', reponse:'Réponse selon les propositions (ex. : Lyon, Marseille, Toulouse).', source:['csp']},
  {theme:'Histoire, géographie et culture', question:'Quel océan borde la côte ouest française ?', reponse:'L\'océan Atlantique.', source:['csp']},
  {theme:'Histoire, géographie et culture', question:'Qu\'est-ce que Paris ?', reponse:'La capitale de la France.', source:['csp']},
  {theme:'Histoire, géographie et culture', question:'Quelle est la capitale de la France ?', reponse:'Paris.', source:['csp']},
  {theme:'Histoire, géographie et culture', question:'Sur quel continent se situe la France métropolitaine ?', reponse:'L\'Europe.', source:['csp']},
  {theme:'Histoire, géographie et culture', question:'Quelle île est un département d\'outre-mer français ?', reponse:'Réponse selon les propositions (ex. : la Réunion, la Martinique, la Guadeloupe).', source:['csp']},
  {theme:'Histoire, géographie et culture', question:'Combien y a-t-il de régions en France métropolitaine ?', reponse:'13.', source:['csp']},
  {theme:'Histoire, géographie et culture', question:'Quelle ville est un grand port maritime ?', reponse:'Réponse selon les propositions (ex. : Marseille, Le Havre).', source:['csp']},
  {theme:'Histoire, géographie et culture', question:'Quelle est la mer au sud de la France métropolitaine ?', reponse:'La mer Méditerranée.', source:['csp']},
  {theme:'Histoire, géographie et culture', question:'Quelle ville est située au bord de la mer Méditerranée ?', reponse:'Réponse selon les propositions (ex. : Marseille, Nice, Montpellier).', source:['csp']},
  {theme:'Histoire, géographie et culture', question:'Où se situe la Corse ?', reponse:'En mer Méditerranée, au sud-est de la France continentale.', source:['csp']},
  {theme:'Histoire, géographie et culture', question:'Quelle chaîne de montagnes est située entre la France et l\'Italie ?', reponse:'Les Alpes.', source:['csp']},
  {theme:'Histoire, géographie et culture', question:'Qui était Molière ?', reponse:'Un auteur et acteur de théâtre français du XVIIe siècle.', source:['csp']},
  {theme:'Histoire, géographie et culture', question:'Qui était Charles Baudelaire ?', reponse:'Un poète français du XIXe siècle, auteur des Fleurs du mal.', source:['csp']},
  {theme:'Histoire, géographie et culture', question:'Qui était George Sand ?', reponse:'Une écrivaine française du XIXe siècle.', source:['csp']},
  {theme:'Histoire, géographie et culture', question:'Qui était Simone de Beauvoir ?', reponse:'Une écrivaine et philosophe féministe française.', source:['csp']},
  {theme:'Histoire, géographie et culture', question:'Qui était Albert Camus ?', reponse:'Un écrivain et philosophe français, prix Nobel de littérature.', source:['csp']},
  {theme:'Histoire, géographie et culture', question:'Qui était Paul Cézanne ?', reponse:'Un peintre français, précurseur du cubisme.', source:['csp']},
  {theme:'Histoire, géographie et culture', question:'Qui était Marc Chagall ?', reponse:'Un peintre franco-russe.', source:['csp']},
  {theme:'Histoire, géographie et culture', question:'Qui était Joséphine Baker ?', reponse:'Une artiste franco-américaine, résistante, entrée au Panthéon.', source:['csp']},
  {theme:'Histoire, géographie et culture', question:'Qui était une chanteuse française célèbre ?', reponse:'Réponse selon les propositions (ex. : Édith Piaf).', source:['csp']},
  {theme:'Histoire, géographie et culture', question:'Qu\'est-ce que le Louvre ?', reponse:'Un grand musée d\'art situé à Paris.', source:['csp']},
  {theme:'Histoire, géographie et culture', question:'Qui était Jean de la Fontaine ?', reponse:'Un poète français, auteur des Fables.', source:['csp']},
  {theme:'Histoire, géographie et culture', question:'Quel écrivain est français ?', reponse:'Réponse selon les propositions (ex. : Victor Hugo, Molière).', source:['csp']},
  {theme:'Histoire, géographie et culture', question:'Dans quelle ville se trouve la tour Eiffel ?', reponse:'Paris.', source:['csp']},
  {theme:'Histoire, géographie et culture', question:'Quand célèbre-t-on Noël ?', reponse:'Le 25 décembre.', source:['csp']},
  {theme:'Vivre dans la société française', question:'Quel numéro d\'urgence permet d\'appeler le SAMU ?', reponse:'Le 15.', source:['csp']},
  {theme:'Vivre dans la société française', question:'Quel numéro d\'urgence permet d\'appeler les pompiers ?', reponse:'Le 18.', source:['csp']},
  {theme:'Vivre dans la société française', question:'Après avoir obtenu le permis de conduire, que faut-il faire pour pouvoir conduire sa voiture ?', reponse:'Assurer le véhicule (assurance obligatoire) et l\'immatriculer.', source:['csp']},
  {theme:'Vivre dans la société française', question:'À quelles conditions un mariage est-il reconnu juridiquement ?', reponse:'S\'il est célébré civilement à la mairie, devant un officier d\'état civil.', source:['csp']},
  {theme:'Vivre dans la société française', question:'Quand faut-il déclarer son enfant au service d\'état civil de la mairie ?', reponse:'Dans les 5 jours suivant la naissance.', source:['csp']},
  {theme:'Vivre dans la société française', question:'Le travail non déclaré est :', reponse:'Interdit et sanctionné (travail dissimulé).', source:['csp']},
  {theme:'Vivre dans la société française', question:'Que doit faire un employeur pour fixer un salaire ?', reponse:'Respecter au minimum le SMIC et la convention collective applicable.', source:['csp']},
  {theme:'Vivre dans la société française', question:'Qu\'est-ce que le SMIC ?', reponse:'Le salaire minimum interprofessionnel de croissance, salaire minimum légal en France.', source:['csp']},
  {theme:'Vivre dans la société française', question:'Quelle est la première démarche à réaliser pour chercher un emploi ?', reponse:'S\'inscrire à France Travail (ex-Pôle emploi).', source:['csp']},
  {theme:'Vivre dans la société française', question:'Quelle est la durée légale du temps de travail par semaine ?', reponse:'35 heures.', source:['csp']},
  {theme:'Vivre dans la société française', question:'Qui est aidé par France Travail ?', reponse:'Les personnes qui recherchent un emploi.', source:['csp']},
  {theme:'Vivre dans la société française', question:'Une personne étrangère en situation régulière peut créer son entreprise :', reponse:'Oui, si son titre de séjour l\'y autorise.', source:['csp']},
  {theme:'Vivre dans la société française', question:'Une femme peut-elle créer son entreprise ?', reponse:'Oui, librement, comme un homme.', source:['csp']},
  {theme:'Vivre dans la société française', question:'À partir de quel âge un mineur peut-il travailler ?', reponse:'16 ans en principe (14 ans sous conditions, pendant les vacances scolaires).', source:['csp']},
  {theme:'Vivre dans la société française', question:'Auprès de quel organisme faut-il demander le remboursement des frais de santé ?', reponse:'La Caisse primaire d\'assurance maladie (Sécurité sociale).', source:['csp']},
  {theme:'Vivre dans la société française', question:'Qu\'est-ce qu\'un numéro d\'urgence ?', reponse:'Un numéro gratuit permettant d\'alerter les services de secours.', source:['csp']},
  {theme:'Vivre dans la société française', question:'Concernant l\'accès aux soins, quelle proposition est correcte ?', reponse:'Toute personne peut être soignée, y compris en urgence, quelle que soit sa situation.', source:['csp','cr']},
  {theme:'Vivre dans la société française', question:'En cas de problème de santé non urgent, à qui faut-il s\'adresser en premier ?', reponse:'Au médecin traitant (médecin généraliste).', source:['csp']},
  {theme:'Vivre dans la société française', question:'Quel est le rôle du médecin traitant ?', reponse:'Suivre la santé du patient et l\'orienter vers des spécialistes si besoin.', source:['csp']},
  {theme:'Vivre dans la société française', question:'Dans quelles situations doit-on se rendre aux urgences de l\'hôpital ?', reponse:'En cas d\'urgence vitale ou de situation grave nécessitant des soins immédiats.', source:['csp']},
  {theme:'Vivre dans la société française', question:'Quel est l\'objectif des vaccinations obligatoires ?', reponse:'Protéger la santé individuelle et collective contre certaines maladies.', source:['csp']},
  {theme:'Vivre dans la société française', question:'À quoi sert la carte Vitale ?', reponse:'À justifier des droits à l\'assurance maladie et faciliter le remboursement des soins.', source:['csp']},
  {theme:'Vivre dans la société française', question:'À quoi sert une mutuelle santé ?', reponse:'À compléter le remboursement de la Sécurité sociale sur la part non prise en charge.', source:['csp']},
  {theme:'Vivre dans la société française', question:'Jusqu\'à quel âge l\'école est-elle obligatoire ?', reponse:'16 ans.', source:['csp']},
  {theme:'Vivre dans la société française', question:'L\'autorité parentale prévoit l\'obligation :', reponse:'D\'assurer la santé, la sécurité, l\'éducation et l\'entretien de l\'enfant.', source:['csp']},
  {theme:'Vivre dans la société française', question:'Pour qui l\'école est-elle obligatoire ?', reponse:'Tous les enfants de 3 à 16 ans résidant en France.', source:['csp']},
  {theme:'Vivre dans la société française', question:'Quel diplôme obtient-on à la fin du lycée ?', reponse:'Le baccalauréat.', source:['csp']},
  {theme:'Vivre dans la société française', question:'Dans quels établissements scolaires vont les élèves après l\'école élémentaire ?', reponse:'Le collège.', source:['csp']},
  {theme:'Vivre dans la société française', question:'Un enfant inscrit à l\'école :', reponse:'A le droit d\'y être scolarisé, quelle que soit la situation administrative de ses parents.', source:['csp']},
  {theme:'Vivre dans la société française', question:'Les enfants qui ne parlent pas français :', reponse:'Bénéficient d\'un accompagnement spécifique pour apprendre le français à l\'école.', source:['csp']},
  {theme:'Principes et valeurs de la République', question:'Parmi les propositions suivantes, laquelle constitue une participation citoyenne ?', reponse:'Voter aux élections, s\'engager dans une association ou faire du bénévolat.', source:['cr']},
  {theme:'Principes et valeurs de la République', question:'Que garantit la liberté d\'expression ?', reponse:'Le droit de dire, écrire et exprimer ses opinions librement, dans le respect de la loi (pas d\'injure, de diffamation ni d\'incitation à la haine).', source:['cr']},
  {theme:'Principes et valeurs de la République', question:'À quoi sert un titre de séjour ?', reponse:'Il permet à un étranger de résider légalement en France et d\'y exercer certains droits (travail, soins…) selon son type.', source:['cr']},
  {theme:'Principes et valeurs de la République', question:'La liberté de circulation permet à toute personne de :', reponse:'Se déplacer librement sur le territoire, y entrer et le quitter, dans le respect des lois.', source:['cr']},
  {theme:'Principes et valeurs de la République', question:'Sur quel site internet peut-on retrouver le symbole de la République française ?', reponse:'Sur le site officiel de l\'administration française, service-public.fr.', source:['cr']},
  {theme:'Principes et valeurs de la République', question:'Complétez ces paroles de la Marseillaise : "Aux armes […] ! Formez vos bataillons"', reponse:'« Aux armes, citoyens ! »', source:['cr']},
  {theme:'Principes et valeurs de la République', question:'Complétez les paroles de la Marseillaise : "Allons enfants de la patrie […]"', reponse:'« Allons enfants de la patrie, le jour de gloire est arrivé ! »', source:['cr']},
  {theme:'Principes et valeurs de la République', question:'En application de la liberté individuelle, quelle proposition est correcte ? Une personne peut :', reponse:'Choisir librement son mode de vie, ses opinions et sa religion, tant qu\'elle respecte la loi et les droits d\'autrui.', source:['cr']},
  {theme:'Principes et valeurs de la République', question:'Concernant la pratique de la religion, quelle proposition est correcte ?', reponse:'Chacun est libre de pratiquer la religion de son choix, ou de n\'en pratiquer aucune, dans le respect de l\'ordre public.', source:['cr']},
  {theme:'Principes et valeurs de la République', question:'En tant que parent, peut-on refuser que son enfant participe aux cours de sport à l\'école car ils sont mixtes ?', reponse:'Non : l\'école publique est laïque et mixte, les cours obligatoires ne peuvent être refusés pour ce motif.', source:['cr']},
  {theme:'Principes et valeurs de la République', question:'Quelle est la devise de la France ?', reponse:'« Liberté, Égalité, Fraternité ».', source:['cr']},
  {theme:'Principes et valeurs de la République', question:'La répudiation de sa femme est :', reponse:'Interdite et non reconnue en droit français, car contraire à l\'égalité entre époux.', source:['cr']},
  {theme:'Principes et valeurs de la République', question:'Les impôts permettent de financer les dépenses publiques. Quelle proposition est correcte ?', reponse:'Ils financent les services publics (écoles, hôpitaux, sécurité, infrastructures) ; payer ses impôts est une obligation légale.', source:['cr']},
  {theme:'Principes et valeurs de la République', question:'Peut-on brûler publiquement un drapeau français ?', reponse:'Non, c\'est une infraction pénale : l\'outrage au drapeau est puni par la loi.', source:['cr']},
  {theme:'Principes et valeurs de la République', question:'Que fait l\'État pour lutter contre les discriminations ?', reponse:'Il légifère (lois anti-discrimination), sanctionne les auteurs et soutient des organismes comme le Défenseur des droits.', source:['cr']},
  {theme:'Principes et valeurs de la République', question:'Que représente Marianne ?', reponse:'L\'allégorie de la République française et de ses valeurs : liberté, égalité, fraternité.', source:['cr']},
  {theme:'Principes et valeurs de la République', question:'Qu\'est-ce que la liberté d\'association ?', reponse:'Le droit de créer librement une association ou d\'y adhérer, dans le respect de la loi.', source:['cr']},
  {theme:'Principes et valeurs de la République', question:'Qu\'est-ce que la liberté ?', reponse:'Le droit de faire tout ce qui ne nuit pas à autrui, dans le respect de la loi.', source:['cr']},
  {theme:'Principes et valeurs de la République', question:'Sur quel document peut-on voir Marianne ?', reponse:'Sur les timbres, les pièces de monnaie, ou le buste présent dans les mairies.', source:['cr']},
  {theme:'Principes et valeurs de la République', question:'Un employeur refuse d\'embaucher des femmes dans son entreprise. Que dit la loi ?', reponse:'C\'est interdit : la loi interdit toute discrimination liée au sexe lors de l\'embauche.', source:['cr']},
  {theme:'Principes et valeurs de la République', question:'Une des valeurs de la devise républicaine est l\'égalité. Qu\'est-ce que cela signifie ?', reponse:'Tous les citoyens ont les mêmes droits et devoirs, sans distinction d\'origine, de sexe, de religion ou de condition sociale.', source:['cr']},
  {theme:'Principes et valeurs de la République', question:'À l\'école publique, qui peut porter des signes religieux très visibles ?', reponse:'Personne : le port de signes religieux ostensibles est interdit pour les élèves des écoles, collèges et lycées publics.', source:['cr']},
  {theme:'Principes et valeurs de la République', question:'Selon le principe de laïcité, que signifie la neutralité de l\'État ?', reponse:'L\'État ne favorise ni ne défavorise aucune religion et garantit leur libre exercice dans le respect de l\'ordre public.', source:['cr']},
  {theme:'Principes et valeurs de la République', question:'Que peut faire un usager du service public dans une mairie ?', reponse:'Être reçu et traité de façon égale, sans discrimination, par des agents publics neutres.', source:['cr']},
  {theme:'Principes et valeurs de la République', question:'Qui doit respecter le principe de neutralité religieuse dans une préfecture ?', reponse:'Les agents publics (fonctionnaires) qui y travaillent.', source:['cr']},
  {theme:'Principes et valeurs de la République', question:'La laïcité impose-t-elle aux agents publics d\'être neutres vis-à-vis des usagers ?', reponse:'Oui, les agents publics doivent rester neutres et ne peuvent porter de signes religieux dans l\'exercice de leurs fonctions.', source:['cr']},
  {theme:'Principes et valeurs de la République', question:'Que garantit le principe de laïcité ?', reponse:'La séparation des religions et de l\'État, la liberté de conscience et l\'égalité de tous devant la loi quelle que soit leur religion.', source:['cr']},
  {theme:'Principes et valeurs de la République', question:'A-t-on le droit de changer de religion ?', reponse:'Oui, la liberté de conscience et de religion permet de changer de religion ou de n\'en avoir aucune.', source:['cr']},
  {theme:'Principes et valeurs de la République', question:'Que représente la laïcité ?', reponse:'Le principe de séparation entre l\'État et les religions, garantissant la neutralité de l\'État et la liberté de croyance.', source:['cr']},
  {theme:'Principes et valeurs de la République', question:'Qu\'est ce qui est interdit par la Charte de la laïcité à l\'école ?', reponse:'Le prosélytisme religieux et le port de signes religieux ostensibles.', source:['cr']},
  {theme:'Principes et valeurs de la République', question:'Que dit l\'article 1er de la Constitution française ?', reponse:'Que la France est une République indivisible, laïque, démocratique et sociale, qui assure l\'égalité devant la loi de tous les citoyens sans distinction.', source:['cr']},
  {theme:'Système institutionnel et politique', question:'Qu\'est-ce que l\'État de droit ?', reponse:'Un système où l\'État lui-même est soumis au respect du droit, et où les droits des citoyens sont garantis par des lois et des tribunaux indépendants.', source:['cr']},
  {theme:'Système institutionnel et politique', question:'Le président de la République a commis un crime. Quelle proposition est correcte ?', reponse:'Il n\'est pas au-dessus des lois : il peut être jugé, notamment après la fin de son mandat, ou par la Haute Cour en cas de manquement grave à ses devoirs.', source:['cr']},
  {theme:'Système institutionnel et politique', question:'La loi est l\'expression de :', reponse:'La volonté générale, votée par le Parlement (Assemblée nationale et Sénat) qui représente les citoyens.', source:['cr']},
  {theme:'Système institutionnel et politique', question:'Quelle est la durée du mandat du conseil municipal et du maire ?', reponse:'6 ans.', source:['cr']},
  {theme:'Système institutionnel et politique', question:'Que garantit l\'État de droit ?', reponse:'Que nul, y compris l\'État, n\'est au-dessus de la loi, et que les droits et libertés des citoyens sont protégés par la justice.', source:['cr']},
  {theme:'Système institutionnel et politique', question:'Une personne peut-elle voter à la place d\'une autre ?', reponse:'Non, c\'est interdit (fraude électorale), sauf en cas de procuration légale.', source:['cr']},
  {theme:'Système institutionnel et politique', question:'Est-ce que le vote est obligatoire ?', reponse:'Non, voter est un droit en France, pas une obligation.', source:['cr']},
  {theme:'Système institutionnel et politique', question:'À la fin de son mandat, le président de la République peut-il décider de rester au pouvoir ?', reponse:'Non, il doit se soumettre à une nouvelle élection ; son pouvoir est limité par la Constitution.', source:['cr']},
  {theme:'Système institutionnel et politique', question:'Qui dirige l\'action du Gouvernement ?', reponse:'Le Premier ministre.', source:['cr']},
  {theme:'Système institutionnel et politique', question:'Quelle est l\'organisation administrative de la France ?', reponse:'Elle est organisée en régions, départements et communes.', source:['cr']},
  {theme:'Système institutionnel et politique', question:'Qu\'est-ce que le pouvoir législatif ? Le pouvoir :', reponse:'Le pouvoir de voter les lois, exercé par le Parlement (Assemblée nationale et Sénat).', source:['cr']},
  {theme:'Système institutionnel et politique', question:'Pourquoi séparer les trois pouvoirs dans une démocratie ?', reponse:'Pour éviter la concentration du pouvoir et les abus, et garantir un équilibre entre exécutif, législatif et judiciaire.', source:['cr']},
  {theme:'Système institutionnel et politique', question:'Quel est le rôle du gouvernement ?', reponse:'Déterminer et conduire la politique de la nation et faire appliquer les lois (pouvoir exécutif).', source:['cr']},
  {theme:'Système institutionnel et politique', question:'Qu\'est-ce que l\'Hôtel de Matignon ?', reponse:'La résidence officielle et le lieu de travail du Premier ministre.', source:['cr']},
  {theme:'Système institutionnel et politique', question:'Quel est le rôle du président de la République ?', reponse:'Chef de l\'État et garant de la Constitution, il nomme le Premier ministre et représente la France.', source:['cr']},
  {theme:'Système institutionnel et politique', question:'Quel est le rôle du Premier ministre ?', reponse:'Diriger l\'action du gouvernement et faire appliquer les lois.', source:['cr']},
  {theme:'Système institutionnel et politique', question:'Qui est le chef du Gouvernement ?', reponse:'Le Premier ministre.', source:['cr']},
  {theme:'Système institutionnel et politique', question:'Combien y a-t-il de régions en France ?', reponse:'18 régions (13 en métropole et 5 en outre-mer).', source:['cr']},
  {theme:'Système institutionnel et politique', question:'Quel est le rôle du Défenseur des droits ?', reponse:'Défendre les droits et libertés des citoyens face aux administrations et lutter contre les discriminations.', source:['cr']},
  {theme:'Système institutionnel et politique', question:'Depuis quand l\'euro est-elle la monnaie unique ?', reponse:'Depuis 2002, date de la mise en circulation des pièces et billets en euros.', source:['cr']},
  {theme:'Système institutionnel et politique', question:'Quel est le rôle principal du département ?', reponse:'Gérer l\'action sociale, les collèges et les routes départementales.', source:['cr']},
  {theme:'Système institutionnel et politique', question:'Quel est le rôle principal des communes ?', reponse:'Gérer les écoles primaires, l\'état civil, l\'urbanisme local et les services de proximité.', source:['cr']},
  {theme:'Système institutionnel et politique', question:'Combien de communes environ existe-t-il en France ?', reponse:'Environ 35 000 communes.', source:['cr']},
  {theme:'Système institutionnel et politique', question:'Quel traité concerne la construction de l\'Union européenne ?', reponse:'Le traité de Rome (1957), qui crée la Communauté économique européenne, ancêtre de l\'Union européenne.', source:['cr']},
  {theme:'Système institutionnel et politique', question:'Quel État a quitté l\'Union européenne en 2020 ?', reponse:'Le Royaume-Uni (Brexit).', source:['cr']},
  {theme:'Système institutionnel et politique', question:'Quelle est la devise de l\'Union européenne ?', reponse:'« Unie dans la diversité ».', source:['cr']},
  {theme:'Système institutionnel et politique', question:'Quel est l\'hymne de l\'Union européenne ?', reponse:'L\'Ode à la joie, de Beethoven.', source:['cr']},
  {theme:'Système institutionnel et politique', question:'De quoi est composé le drapeau européen ?', reponse:'De 12 étoiles dorées disposées en cercle sur un fond bleu.', source:['cr']},
  {theme:'Système institutionnel et politique', question:'De quelle couleur est le drapeau européen ?', reponse:'Bleu, avec des étoiles jaunes/dorées.', source:['cr']},
  {theme:'Système institutionnel et politique', question:'En quelle année le traité de Maastricht, qui marque la fondation de l\'Union européenne, a-t-il été signé ?', reponse:'En 1992.', source:['cr']},
  {theme:'Système institutionnel et politique', question:'Où est le siège du Parlement européen ?', reponse:'À Strasbourg.', source:['cr']},
  {theme:'Système institutionnel et politique', question:'Où est le siège de la Commission européenne ?', reponse:'À Bruxelles.', source:['cr']},
  {theme:'Droits et devoirs', question:'À quelle liberté la PMA fait-elle référence ?', reponse:'À la liberté de disposer de son corps et au droit de fonder une famille.', source:['cr']},
  {theme:'Droits et devoirs', question:'Au nom de quoi l\'État justifie-t-il la restriction des droits ?', reponse:'Au nom de l\'ordre public, de la sécurité, ou de la protection des droits d\'autrui et de l\'intérêt général.', source:['cr']},
  {theme:'Droits et devoirs', question:'Concernant le droit de se marier, quelle proposition est correcte ?', reponse:'Toute personne majeure et consentante peut se marier, y compris les couples de même sexe depuis 2013.', source:['cr']},
  {theme:'Droits et devoirs', question:'Laquelle de ces citations est inscrite dans la Déclaration des Droits de l\'homme et du Citoyen de 1789 ?', reponse:'« Les hommes naissent et demeurent libres et égaux en droits » (article 1er).', source:['cr']},
  {theme:'Droits et devoirs', question:'Le recours à l\'avortement est-il autorisé ?', reponse:'Oui, l\'IVG (interruption volontaire de grossesse) est un droit légal en France, inscrit dans la Constitution depuis 2024.', source:['cr']},
  {theme:'Droits et devoirs', question:'Que contient la Constitution ?', reponse:'L\'organisation des pouvoirs publics ainsi que les droits et libertés fondamentaux des citoyens.', source:['cr']},
  {theme:'Droits et devoirs', question:'Que garantit la liberté de la presse ?', reponse:'Le droit d\'informer et d\'être informé librement, dans le respect de la loi (pas de diffamation ni d\'atteinte à la vie privée).', source:['cr']},
  {theme:'Droits et devoirs', question:'Que prévoit la Charte de l\'environnement ?', reponse:'Que chacun a le droit de vivre dans un environnement équilibré et le devoir de le protéger ; elle a valeur constitutionnelle depuis 2005.', source:['cr']},
  {theme:'Droits et devoirs', question:'Que signifie la dignité humaine ?', reponse:'Le respect dû à toute personne humaine, quelle que soit sa situation, interdisant tout traitement dégradant.', source:['cr']},
  {theme:'Droits et devoirs', question:'Que signifie le droit de manifester ?', reponse:'Le droit de se réunir et d\'exprimer publiquement une opinion, dans le respect de la loi et de l\'ordre public.', source:['cr']},
  {theme:'Droits et devoirs', question:'Que signifie PMA ?', reponse:'Procréation médicalement assistée.', source:['cr']},
  {theme:'Droits et devoirs', question:'Quel texte est le plus difficile à modifier ?', reponse:'La Constitution, qui nécessite une procédure de révision spécifique.', source:['cr']},
  {theme:'Droits et devoirs', question:'Quelle liberté permet à une personne de croire en la religion de son choix ?', reponse:'La liberté de conscience et de religion (liberté de culte).', source:['cr']},
  {theme:'Droits et devoirs', question:'Qu\'est-ce que le droit de grève ?', reponse:'Le droit des salariés de cesser collectivement le travail pour défendre leurs revendications.', source:['cr']},
  {theme:'Droits et devoirs', question:'Qu\'est-ce que la Constitution ?', reponse:'Le texte fondamental qui organise les pouvoirs publics et garantit les droits et libertés des citoyens.', source:['cr']},
  {theme:'Droits et devoirs', question:'Qui peut demander à avorter ?', reponse:'Toute femme enceinte qui le souhaite, dans les délais légaux prévus par la loi.', source:['cr']},
  {theme:'Droits et devoirs', question:'Une femme majeure de nationalité française a-t-elle le droit de voter aux élections ?', reponse:'Oui, depuis 1944 les femmes ont les mêmes droits de vote que les hommes.', source:['cr']},
  {theme:'Droits et devoirs', question:'Concernant l\'utilisation des réseaux sociaux, quelle proposition est correcte ?', reponse:'La liberté d\'expression s\'y applique, mais dans les limites de la loi (pas de diffamation, d\'injure ni d\'incitation à la haine).', source:['cr']},
  {theme:'Droits et devoirs', question:'Jeter un mégot par terre est :', reponse:'Interdit et passible d\'une amende (infraction environnementale).', source:['cr']},
  {theme:'Droits et devoirs', question:'L\'État peut-il limiter les droits et libertés ?', reponse:'Oui, dans certaines conditions prévues par la loi, pour protéger l\'ordre public ou les droits d\'autrui.', source:['cr']},
  {theme:'Droits et devoirs', question:'Parmi ces actions, laquelle permet d\'adopter une attitude respectueuse de l\'environnement ?', reponse:'Trier ses déchets, économiser l\'eau et l\'énergie, ou utiliser les transports en commun.', source:['cr']},
  {theme:'Droits et devoirs', question:'Quelle proposition constitue une obligation ?', reponse:'Payer ses impôts, respecter la loi, ou scolariser ses enfants.', source:['cr']},
  {theme:'Droits et devoirs', question:'Pour quel motif peut-on limiter la liberté d\'expression ?', reponse:'Pour éviter la diffamation, l\'injure, l\'incitation à la haine ou à la violence, ou pour protéger l\'ordre public.', source:['cr']},
  {theme:'Droits et devoirs', question:'Pourquoi doit-on trier ses déchets ?', reponse:'Pour protéger l\'environnement et permettre leur recyclage ; c\'est aussi une obligation légale.', source:['cr']},
  {theme:'Droits et devoirs', question:'Que doit-on faire face aux ordres des policiers ou gendarmes ?', reponse:'Les respecter et s\'y conformer, car ils agissent dans le cadre de la loi.', source:['cr']},
  {theme:'Droits et devoirs', question:'Quel est un exemple d\'assistance à personne en danger ?', reponse:'Appeler les secours (15, 17, 18 ou 112) ou porter assistance dans la mesure de ses moyens.', source:['cr']},
  {theme:'Droits et devoirs', question:'Quel exemple illustre une limitation de liberté pour protéger l\'intérêt général ?', reponse:'L\'obligation du port de la ceinture de sécurité, ou l\'interdiction de fumer dans les lieux publics.', source:['cr']},
  {theme:'Droits et devoirs', question:'Quelle est l\'attitude à avoir lorsque qu\'on est témoin de violences ?', reponse:'Alerter les secours ou la police, et porter assistance si possible sans se mettre en danger.', source:['cr']},
  {theme:'Droits et devoirs', question:'Quelle obligation concerne toutes les personnes résidant en France quelle que soit leur nationalité ?', reponse:'Respecter les lois françaises.', source:['cr']},
  {theme:'Droits et devoirs', question:'Quelle proposition représente un exemple de crime ?', reponse:'Le meurtre, le viol ou le vol à main armée.', source:['cr']},
  {theme:'Droits et devoirs', question:'Quelle proposition représente un exemple de délit ?', reponse:'Le vol simple, la conduite en état d\'ivresse, ou des coups et blessures légers.', source:['cr']},
  {theme:'Droits et devoirs', question:'Qui veille au maintien de l\'ordre public ?', reponse:'La police et la gendarmerie.', source:['cr']},
  {theme:'Droits et devoirs', question:'S\'agissant des déchets, quelle proposition est correcte ?', reponse:'Le tri des déchets est une obligation et permet leur recyclage.', source:['cr']},
  {theme:'Histoire, géographie et culture', question:'Quel était le surnom de Louis XIV ?', reponse:'Le Roi-Soleil.', source:['cr']},
  {theme:'Histoire, géographie et culture', question:'Quel roi de France a été exécuté pendant la Révolution française ?', reponse:'Louis XVI.', source:['cr']},
  {theme:'Histoire, géographie et culture', question:'En quelle année Napoléon Ier est-il devenu empereur ?', reponse:'En 1804.', source:['cr']},
  {theme:'Histoire, géographie et culture', question:'Lequel de ces personnages a un lien avec la République française ?', reponse:'Marianne, allégorie de la République, ou une figure historique comme Charles de Gaulle qui l\'a incarnée.', source:['cr']},
  {theme:'Histoire, géographie et culture', question:'De quand date l\'appel à la résistance du général de Gaulle ?', reponse:'Du 18 juin 1940.', source:['cr']},
  {theme:'Histoire, géographie et culture', question:'Pourquoi la Shoah est-elle étudiée à l\'école ?', reponse:'Pour comprendre et se souvenir du génocide des Juifs perpétré par les nazis pendant la Seconde Guerre mondiale, et prévenir toute répétition.', source:['cr']},
  {theme:'Histoire, géographie et culture', question:'Quel pays a été colonisé par la France ?', reponse:'Par exemple l\'Algérie, le Sénégal ou le Vietnam, parmi de nombreux territoires en Afrique, Asie et Amérique.', source:['cr']},
  {theme:'Histoire, géographie et culture', question:'Depuis quand les Français élisent-ils le président de la République au suffrage universel direct ?', reponse:'Depuis 1965 (réforme instaurée en 1962 par le général de Gaulle).', source:['cr']},
  {theme:'Histoire, géographie et culture', question:'Quelle est la première étape de la construction européenne en 1951 ?', reponse:'La création de la Communauté européenne du charbon et de l\'acier (CECA).', source:['cr']},
  {theme:'Histoire, géographie et culture', question:'Durant le mandat de quel président la peine de mort a-t-elle été abolie ?', reponse:'François Mitterrand, en 1981.', source:['cr']},
  {theme:'Histoire, géographie et culture', question:'Quel régime politique a été mis en place pendant la Révolution française en 1792 ?', reponse:'La Première République.', source:['cr']},
  {theme:'Histoire, géographie et culture', question:'Qui était une figure de la Résistance française pendant la Seconde Guerre mondiale ?', reponse:'Jean Moulin (ou le général de Gaulle).', source:['cr']},
  {theme:'Histoire, géographie et culture', question:'En 1944, qu\'est-ce qui a changé pour les femmes ?', reponse:'Elles ont obtenu le droit de vote et d\'éligibilité.', source:['cr']},
  {theme:'Histoire, géographie et culture', question:'Quelle organisation internationale a été créée en 1945 après la Seconde Guerre mondiale ?', reponse:'L\'Organisation des Nations unies (ONU).', source:['cr']},
  {theme:'Histoire, géographie et culture', question:'Quelle peine a été supprimée en 1981 ?', reponse:'La peine de mort.', source:['cr']},
  {theme:'Histoire, géographie et culture', question:'En quelle année l\'euro est-elle devenue la monnaie utilisée en France ?', reponse:'En 2002.', source:['cr']},
  {theme:'Histoire, géographie et culture', question:'En quelle année a commencé la Première Guerre mondiale ?', reponse:'En 1914.', source:['cr']},
  {theme:'Histoire, géographie et culture', question:'Où a eu lieu le débarquement en 1944 ?', reponse:'En Normandie.', source:['cr']},
  {theme:'Histoire, géographie et culture', question:'Quel continent a été le plus concerné par la décolonisation française après la Seconde Guerre mondiale ?', reponse:'L\'Afrique (ainsi que l\'Asie, avec l\'Indochine).', source:['cr']},
  {theme:'Histoire, géographie et culture', question:'Que fête-t-on le 8 mai ?', reponse:'La victoire des Alliés et la fin de la Seconde Guerre mondiale en Europe (armistice de 1945).', source:['cr']},
  {theme:'Histoire, géographie et culture', question:'Quelle mer ou océan borde la France métropolitaine ?', reponse:'La Manche, l\'océan Atlantique et la mer Méditerranée.', source:['cr']},
  {theme:'Histoire, géographie et culture', question:'Quel pays a une frontière terrestre avec la France métropolitaine ?', reponse:'Par exemple l\'Espagne, l\'Italie, l\'Allemagne, la Belgique ou la Suisse.', source:['cr']},
  {theme:'Histoire, géographie et culture', question:'Quelle ville française est un port maritime ?', reponse:'Marseille (ou Le Havre, Bordeaux).', source:['cr']},
  {theme:'Histoire, géographie et culture', question:'Quelle mer se situe entre la France et l\'Angleterre ?', reponse:'La Manche.', source:['cr']},
  {theme:'Histoire, géographie et culture', question:'Qu\'est ce que la France d\'outre-mer ?', reponse:'Les territoires français situés hors d\'Europe (Guadeloupe, Martinique, Guyane, Réunion, Mayotte…), qui font partie intégrante de la République.', source:['cr']},
  {theme:'Histoire, géographie et culture', question:'Quelle chaîne de montagnes est située entre la France et l\'Espagne ?', reponse:'Les Pyrénées.', source:['cr']},
  {theme:'Histoire, géographie et culture', question:'Quelle île française se trouve dans l\'océan Indien ?', reponse:'La Réunion (ou Mayotte).', source:['cr']},
  {theme:'Histoire, géographie et culture', question:'Quelle est la population approximative de la France en 2025 ?', reponse:'Environ 68 millions d\'habitants.', source:['cr']},
  {theme:'Histoire, géographie et culture', question:'Quel fleuve traverse Paris ?', reponse:'La Seine.', source:['cr']},
  {theme:'Histoire, géographie et culture', question:'Lequel de ces pays partage des frontières terrestres avec la France ?', reponse:'L\'Espagne, l\'Italie, la Belgique, l\'Allemagne, la Suisse, le Luxembourg, Andorre ou Monaco.', source:['cr']},
  {theme:'Histoire, géographie et culture', question:'Quel pays a une frontière avec la France métropolitaine au nord-est ?', reponse:'L\'Allemagne (ainsi que le Luxembourg et la Belgique).', source:['cr']},
  {theme:'Histoire, géographie et culture', question:'Où se trouvent les principales activités économiques en France ?', reponse:'Dans les grandes métropoles, avec une forte concentration en Île-de-France.', source:['cr']},
  {theme:'Histoire, géographie et culture', question:'Parmi ces pays, lequel attire le plus de visiteurs chaque année ?', reponse:'La France, première destination touristique mondiale.', source:['cr']},
  {theme:'Histoire, géographie et culture', question:'Où habite la majorité des Français ?', reponse:'En zone urbaine, dans les villes et leurs agglomérations.', source:['cr']},
  {theme:'Histoire, géographie et culture', question:'Quelle région est la plus peuplée ?', reponse:'L\'Île-de-France.', source:['cr']},
  {theme:'Histoire, géographie et culture', question:'Quelle ville française fait partie des 10 plus grandes métropoles du pays ?', reponse:'Par exemple Lyon, Marseille ou Toulouse.', source:['cr']},
  {theme:'Histoire, géographie et culture', question:'Lequel de ces départements de France est le plus touristique ?', reponse:'Paris (ou les Alpes-Maritimes).', source:['cr']},
  {theme:'Histoire, géographie et culture', question:'Quand peut-on visiter gratuitement des lieux culturels en France ?', reponse:'Lors des Journées européennes du patrimoine, en septembre, ou le premier dimanche du mois dans certains musées.', source:['cr']},
  {theme:'Histoire, géographie et culture', question:'Combien de personnes parlent français dans le monde ?', reponse:'Plus de 320 millions de personnes.', source:['cr']},
  {theme:'Histoire, géographie et culture', question:'Qui était Marguerite Yourcenar ?', reponse:'Une écrivaine française, première femme élue à l\'Académie française, en 1980.', source:['cr']},
  {theme:'Histoire, géographie et culture', question:'Quel peintre est français ?', reponse:'Claude Monet (ou Auguste Renoir, Edgar Degas).', source:['cr']},
  {theme:'Histoire, géographie et culture', question:'Quel musée est situé à Paris ?', reponse:'Le Louvre (ou le musée d\'Orsay).', source:['cr']},
  {theme:'Histoire, géographie et culture', question:'Qui était Auguste Rodin ?', reponse:'Un célèbre sculpteur français, auteur notamment du « Penseur ».', source:['cr']},
  {theme:'Histoire, géographie et culture', question:'Quel est le classement de la langue française parmi les langues les plus parlées dans le monde ?', reponse:'Elle figure parmi les cinq langues les plus parlées au monde.', source:['cr']},
  {theme:'Histoire, géographie et culture', question:'Quelle cathédrale célèbre a été en partie détruite par un incendie en 2019 ?', reponse:'Notre-Dame de Paris.', source:['cr']},
  {theme:'Histoire, géographie et culture', question:'Qui était une écrivaine française célèbre ?', reponse:'Simone de Beauvoir (ou George Sand, Marguerite Yourcenar).', source:['cr']},
  {theme:'Histoire, géographie et culture', question:'Qui était un célèbre musicien français ?', reponse:'Claude Debussy (ou Édith Piaf, Hector Berlioz).', source:['cr']},
  {theme:'Histoire, géographie et culture', question:'Qui était Auguste Renoir ?', reponse:'Un peintre impressionniste français.', source:['cr']},
  {theme:'Vivre dans la société française', question:'Quel mariage est reconnu par l\'État ?', reponse:'Le mariage civil célébré à la mairie ; un mariage religieux seul n\'a pas de valeur légale.', source:['cr']},
  {theme:'Vivre dans la société française', question:'Auprès de quelle institution les parents peuvent-ils inscrire leur enfant à l\'école publique ?', reponse:'La mairie.', source:['cr']},
  {theme:'Vivre dans la société française', question:'En cas de divorce, qui exerce l\'autorité parentale ?', reponse:'En général les deux parents (autorité parentale conjointe), sauf décision contraire du juge.', source:['cr']},
  {theme:'Vivre dans la société française', question:'Quelle aide permet aux personnes qui ont des difficultés financières d\'avoir un avocat ?', reponse:'L\'aide juridictionnelle.', source:['cr']},
  {theme:'Vivre dans la société française', question:'Où faut-il déclarer la naissance d\'un enfant ?', reponse:'À la mairie du lieu de naissance, dans les cinq jours suivant la naissance.', source:['cr']},
  {theme:'Vivre dans la société française', question:'Quelle est l\'une des conditions pour passer l\'examen du permis de conduire ?', reponse:'Avoir l\'âge minimum requis (17 ou 18 ans selon le permis) et suivre une formation dans une auto-école.', source:['cr']},
  {theme:'Vivre dans la société française', question:'Un bail locatif est valide s\'il est :', reponse:'Écrit et signé par le propriétaire et le locataire.', source:['cr']},
  {theme:'Vivre dans la société française', question:'Où peut-on déposer un lave-vaisselle cassé ?', reponse:'À la déchetterie.', source:['cr']},
  {theme:'Vivre dans la société française', question:'Quel numéro d\'urgence permet d\'appeler la police ?', reponse:'Le 17 (ou le 112, numéro d\'urgence européen).', source:['cr']},
  {theme:'Vivre dans la société française', question:'À qui est accessible la contraception ?', reponse:'À toutes les femmes, y compris les mineures, souvent de façon gratuite ou remboursée.', source:['cr']},
  {theme:'Vivre dans la société française', question:'Qu\'est-ce que le principe de confidentialité dans le domaine de la santé ?', reponse:'Le secret médical : les informations de santé d\'un patient ne peuvent être divulguées sans son consentement.', source:['cr']},
  {theme:'Vivre dans la société française', question:'L\'inscription à l\'Assurance maladie est :', reponse:'Obligatoire pour toute personne résidant en France.', source:['cr']},
  {theme:'Vivre dans la société française', question:'Qui peut demander un congé parental d\'éducation ?', reponse:'Tout salarié, homme ou femme, à la naissance ou à l\'adoption d\'un enfant.', source:['cr']},
  {theme:'Vivre dans la société française', question:'Quelles sont les affaires traitées par le conseil de prud\'hommes ?', reponse:'Les litiges individuels entre employeurs et salariés liés au contrat de travail.', source:['cr']},
  {theme:'Vivre dans la société française', question:'Travailler sans être déclaré est :', reponse:'Illégal (travail dissimulé) et passible de sanctions pénales.', source:['cr']},
  {theme:'Vivre dans la société française', question:'Lorsqu\'un employeur veut qu\'un salarié travaille plus longtemps que la durée prévue dans le contrat de travail :', reponse:'Il doit rémunérer ces heures supplémentaires, selon les règles légales ou conventionnelles.', source:['cr']},
  {theme:'Vivre dans la société française', question:'Quelle est la mission de France Travail ?', reponse:'Aider les demandeurs d\'emploi à retrouver un emploi et verser les allocations chômage (anciennement Pôle emploi).', source:['cr']},
  {theme:'Vivre dans la société française', question:'Dans une entreprise, le droit syndical permet :', reponse:'Aux salariés de se syndiquer et de défendre collectivement leurs intérêts.', source:['cr']},
  {theme:'Vivre dans la société française', question:'Dans une entreprise, le droit de grève autorise :', reponse:'Les salariés à cesser collectivement le travail pour défendre leurs revendications.', source:['cr']},
  {theme:'Vivre dans la société française', question:'Quelles sont les conditions pour toucher les allocations chômage ?', reponse:'Avoir suffisamment cotisé, être inscrit comme demandeur d\'emploi et rechercher activement un emploi.', source:['cr']},
  {theme:'Vivre dans la société française', question:'Qu\'est-ce que l\'école maternelle ?', reponse:'L\'école destinée aux enfants de 3 à 6 ans, avant l\'école élémentaire ; elle est obligatoire dès 3 ans.', source:['cr']},
  {theme:'Vivre dans la société française', question:'Comment s\'appelle le diplôme passé par les élèves à la fin du collège ?', reponse:'Le brevet (Diplôme national du brevet).', source:['cr']},
  {theme:'Vivre dans la société française', question:'Les parents d\'élève ont le droit de :', reponse:'Être informés de la scolarité de leur enfant et participer aux instances de l\'école (conseil d\'école…).', source:['cr']},
  {theme:'Vivre dans la société française', question:'Qui peut manger à la cantine scolaire ?', reponse:'Tous les élèves inscrits, sans discrimination.', source:['cr']},
  {theme:'Vivre dans la société française', question:'À quel âge commence l\'instruction obligatoire des enfants ?', reponse:'3 ans.', source:['cr']},
  {theme:'Vivre dans la société française', question:'Quel est l\'âge de la majorité ?', reponse:'18 ans.', source:['cr']},
  {theme:'Vivre dans la société française', question:'À l\'école, il est interdit aux parents de :', reponse:'Faire du prosélytisme religieux ou politique, ou pénétrer dans les classes sans autorisation.', source:['cr']},
  {theme:'Vivre dans la société française', question:'Quel motif d\'absence est accepté par l\'école ?', reponse:'La maladie de l\'enfant, justifiée par un certificat médical ou une note des parents.', source:['cr']},
  {theme:'Vivre dans la société française', question:'Des parents ne respectent pas l\'obligation d\'instruction pour leurs enfants. Quelle sanction maximale risquent-ils ?', reponse:'Une amende pouvant aller jusqu\'à 750 €, voire des poursuites pénales dans les cas graves.', source:['cr']},
  {theme:'Vivre dans la société française', question:'Quand ont lieu les vacances scolaires de Noël ?', reponse:'Fin décembre, généralement pendant environ deux semaines à la charnière de l\'année.', source:['cr']},
];